Update copy_parse_markdown.yml

diff --git a/.github/workflows/copy_parse_markdown.yml b/.github/workflows/copy_parse_markdown.yml
--- a/.github/workflows/copy_parse_markdown.yml
+++ b/.github/workflows/copy_parse_markdown.yml
@@ -26,9 +26,18 @@ jobs:
       SOURCE_FILE_PATH: ${{ github.workspace }}/${{ github.event.inputs.code_directory }}/markdown_to_json_parser_new.py
 
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Download source file
         run: |
-          mkdir -p "${{ github.workspace }}/${{ github.event.inputs.code_directory }}"
+          if mkdir -p "${{ github.workspace }}/${{ github.event.inputs.code_directory }}"; then
+            echo "Directory created successfully or already existed."
+          else
+            echo "Failed to create directory."
+            exit 1
+          fi
+
           source_url="https://raw.githubusercontent.com/${{ github.event.inputs.source_repo }}/main/${{ github.event.inputs.source_file_path }}"
           curl -o "${{ env.SOURCE_FILE_PATH }}" "$source_url"
           echo "File downloaded successfully"
