Update copy_parse_markdown.yml

diff --git a/.github/workflows/copy_parse_markdown.yml b/.github/workflows/copy_parse_markdown.yml
--- a/.github/workflows/copy_parse_markdown.yml
+++ b/.github/workflows/copy_parse_markdown.yml
@@ -26,6 +26,9 @@ jobs:
   copy-code:
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: write
+
     env:
       SOURCE_FILE_PATH: ${{ github.workspace }}/${{ github.event.inputs.code_directory }}/markdown_to_json_parser_new.py
       SOURCE_DESTINATION_FILE_PATH: ${{ github.workspace }}/${{ github.event.inputs.source_file_path }}
@@ -33,6 +36,27 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        continue-on-error: true # Continue with the workflow even if the checkout fails
+        with:
+          ref: ${{ github.event.before || 'main' }}
+
+      - name: Define show_file_content function
+        run: |
+          set -e
+          show_file_content() {
+            local file_path=$1
+
+            if [[ -f "$file_path" ]]; then
+              if [[ "${{ github.event.inputs.display_file_contents }}" == 'true' ]]; then
+                echo "Displaying content of the file:"
+                cat "$file_path"
+              else
+                echo "Displaying content is blocked."
+              fi
+            else
+              echo "File does not exist."
+            fi
+          }
 
       - name: Download source file
         run: |
@@ -44,52 +68,68 @@ jobs:
           fi
 
           source_url="https://raw.githubusercontent.com/${{ github.event.inputs.source_repo }}/main/${{ github.event.inputs.source_file_path }}"
-          curl -o "${{ env.SOURCE_FILE_PATH }}" "$source_url"
-          echo "File downloaded successfully"
-
-      - name: Display content of the downloaded source file
-        run: |
-          if [ -f "${{ env.SOURCE_FILE_PATH }}" ]; then
-            if [ "${{ github.event.inputs.display_file_contents }}" == 'true' ]; then
-              cat "${{ env.SOURCE_FILE_PATH }}"
-            else
-              echo "Displaying content is blocked."
-            fi
+          if curl -o "${{ env.SOURCE_FILE_PATH }}" "$source_url"; then
+            echo "Source file downloaded successfully."
           else
-            echo "Source file does not exist."
+            echo "Failed to download source file."
             exit 1
           fi
 
+      - name: Display content of the downloaded source file
+        run: |
+          show_file_content "${{ env.SOURCE_FILE_PATH }}"
+
       - name: Display content of destination file from target repository
         run: |
-          if [ -f "${{ env.SOURCE_DESTINATION_FILE_PATH }}" ]; then
-            if [ "${{ github.event.inputs.display_file_contents }}" == 'true' ]; then
-              cat "${{ env.SOURCE_DESTINATION_FILE_PATH }}"
-            else
-              echo "Displaying content is blocked."
-            fi
-          else
-            echo "Source file does not exist."
-          fi
+          show_file_content "${{ env.SOURCE_DESTINATION_FILE_PATH }}"
 
       - name: Compare and handle files
         run: |
-          if [ -f "${{ env.SOURCE_DESTINATION_FILE_PATH }}" ]; then
-            if cmp -s "${{ env.SOURCE_DESTINATION_FILE_PATH }}" "${{ env.SOURCE_FILE_PATH }}"; then
-              echo "Files are equal. Deleting SOURCE_FILE_PATH."
+          set -e
+
+          handle_equal_files() {
+            echo "Files are equal. Deleting SOURCE_FILE_PATH."
+            if rm "${{ env.SOURCE_FILE_PATH }}"; then
+              echo "SOURCE_FILE_PATH deleted successfully."
+            else
+              echo "Failed to delete SOURCE_FILE_PATH."
+              exit 1
+            fi
+          }
+
+          handle_unequal_files() {
+            echo "Files are not equal. Replacing SOURCE_DESTINATION_FILE_PATH with content from SOURCE_FILE_PATH."
+            if cat "${{ env.SOURCE_FILE_PATH }}" > "${{ env.SOURCE_DESTINATION_FILE_PATH }}"; then
+              echo "SOURCE_DESTINATION_FILE_PATH replaced successfully."
               rm "${{ env.SOURCE_FILE_PATH }}"
             else
-              echo "Files are not equal. Replacing SOURCE_DESTINATION_FILE_PATH with content from SOURCE_FILE_PATH."
-              cat "${{ env.SOURCE_FILE_PATH }}" > "${{ env.SOURCE_DESTINATION_FILE_PATH }}"
-              rm "${{ env.SOURCE_FILE_PATH }}"
+              echo "Failed to replace SOURCE_DESTINATION_FILE_PATH."
+              exit 1
             fi
-          else
+          }
+
+          handle_missing_destination() {
             echo "SOURCE_DESTINATION_FILE_PATH does not exist. Renaming SOURCE_FILE_PATH to SOURCE_DESTINATION_FILE_PATH."
             if [ -f "${{ env.SOURCE_FILE_PATH }}" ] && [ -f "${{ env.SOURCE_DESTINATION_FILE_PATH }}" ]; then
-              mv "${{ env.SOURCE_FILE_PATH }}" "${{ env.SOURCE_DESTINATION_FILE_PATH }}"
+              if mv "${{ env.SOURCE_FILE_PATH }}" "${{ env.SOURCE_DESTINATION_FILE_PATH }}"; then
+                echo "Files renamed successfully."
+              else
+                echo "Failed to rename files."
+                exit 1
+              fi
             else
               echo "One or both of the files do not exist."
             fi
+          }
+
+          if [ -f "${{ env.SOURCE_DESTINATION_FILE_PATH }}" ]; then
+            if cmp -s "${{ env.SOURCE_DESTINATION_FILE_PATH }}" "${{ env.SOURCE_FILE_PATH }}"; then
+              handle_equal_files
+            else
+              handle_unequal_files
+            fi
+          else
+            handle_missing_destination
           fi
 
       - name: Display working code directory content
